//! Upload twenty million generated bytes to a Discord webhook.
//!
//! Run with `DISCORD_WEBHOOK_URL=... cargo run --example webhook_upload --features tokio-tcp-pool`.

use std::{error::Error, sync::Arc, time::Instant};

use discord_webhook_storage::{WebhookCredentials, WriteConfig, WriteFile};
use futures::AsyncWriteExt;
use tokio_tcp_pool::{Pool, Route, rustls};

const FILE_SIZE: usize = 5_000_000;
const WRITE_SIZE: usize = 64 * 1024;

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    let url = std::env::var("DISCORD_WEBHOOK_URL")?;
    let credentials = WebhookCredentials::parse(&url)?;

    let roots = rustls::RootCertStore::from_iter(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());

    let tls = rustls::ClientConfig::builder()
        .with_root_certificates(roots)
        .with_no_client_auth();

    let pool = Pool::builder(Route::Direct {
        target: "discord.com:443".parse()?,
    })
    .max_open(1)
    .tls(Arc::new(tls))
    .build()?;

    // DO 2 Uploads
    for i in 0..4 {
        let now = Instant::now();
        println!("Upload {i} : Acquiring connection for upload");
        let mut connection = pool.acquire().await?;
        println!(
            "Upload {i} : Acquired connection for upload - took {:?}",
            now.elapsed()
        );
        let now = Instant::now();

        let mut file =
            WriteFile::open(&mut connection, &credentials, &WriteConfig::default()).await?;
        println!(
            "Upload {i} : Opened file for upload - took {:?}",
            now.elapsed()
        );
        let now = Instant::now();

        let pattern: Vec<u8> = (0..WRITE_SIZE).map(|i| (i & 0xff) as u8).collect();

        let mut remaining = FILE_SIZE;

        while remaining > 0 {
            let count = remaining.min(pattern.len());
            file.write_all(&pattern[..count]).await?;
            remaining -= count;
        }
        println!(
            "Upload {i} : Finished writing file - took {:?}",
            now.elapsed()
        );

        let now = Instant::now();
        match file.finish().await {
            Ok(result) => {
                println!("{}", serde_json::to_string(&result)?);
                connection.release();
            }
            Err(e) => {
                println!("Error finishing upload: {e}");
                connection.discard();
            }
        };
        println!(
            "Upload {i} : Finished writing file - took {:?}",
            now.elapsed()
        );
    }

    Ok(())
}
