//! Upload generated bytes, download a range, and compare it with the original.
//!
//! Run with `DISCORD_WEBHOOK_URL=... cargo run --example webhook_upload_download --features tokio-tcp-pool`.
//! The uploaded attachment remains in the webhook's channel after the example.

use std::{error::Error, io, sync::Arc};

use discord_webhook_storage::{ReadFile, WebhookCredentials, WriteConfig, WriteFile};
use futures::{AsyncReadExt, AsyncWriteExt};
use tokio_tcp_pool::{Pool, Route, rustls};

const FILE_SIZE: usize = 1024 * 1024;
const RANGE_START: usize = 12_345;
const RANGE_END: usize = RANGE_START + 64 * 1024 - 1;

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    let webhook_url = std::env::var("DISCORD_WEBHOOK_URL")?;
    let credentials = WebhookCredentials::parse(&webhook_url)?;

    let roots = rustls::RootCertStore::from_iter(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());
    let tls = Arc::new(
        rustls::ClientConfig::builder()
            .with_root_certificates(roots)
            .with_no_client_auth(),
    );

    let upload_pool = Pool::builder(Route::Direct {
        target: "discord.com:443".parse()?,
    })
    .max_open(1)
    .tls(Arc::clone(&tls))
    .build()?;

    let download_pool = Pool::builder(Route::Direct {
        target: "cdn.discordapp.com:443".parse()?,
    })
    .max_open(1)
    .tls(tls)
    .build()?;

    let payload: Vec<u8> = (0..FILE_SIZE).map(|offset| (offset % 251) as u8).collect();
    let file = {
        let mut connection = upload_pool.acquire().await?;
        let mut writer =
            WriteFile::open(&mut connection, &credentials, &WriteConfig::default()).await?;
        writer.write_all(&payload).await?;
        let file = writer.finish().await?;
        // Release only after finish succeeds. Errors drop the unreleased connection.
        connection.release();
        file
    };
    println!("Uploaded {FILE_SIZE} bytes in message {}", file.id);

    let mut connection = download_pool.acquire().await?;
    let mut downloaded = Vec::new();
    {
        let mut reader =
            ReadFile::open_with_range(&mut connection, &file, RANGE_START, Some(RANGE_END)).await?;
        // Read through EOF before dropping the reader and releasing the connection.
        reader.read_to_end(&mut downloaded).await?;
    }

    let expected = &payload[RANGE_START..=RANGE_END];
    if downloaded.as_slice() != expected {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "range {RANGE_START}-{RANGE_END} differs from the upload: expected {} bytes, received {}",
                expected.len(),
                downloaded.len(),
            ),
        )
        .into());
    }
    connection.release();
    println!(
        "Verified {} downloaded bytes for range {RANGE_START}-{RANGE_END} (inclusive)",
        downloaded.len(),
    );

    Ok(())
}
